= Federation of Intersectional Communities
Justin W. Flory
v0.0.1
:page-excerpt: Concept note (draft) for the Federation of Intersectional Communities, its goals and values, and more.
:page-layout: default
:page-liquid:
:revdate: 2020-09-07
:toc:
:_txt-convener: Justin W. Flory

*DRAFT DRAFT DRAFT*

[link=https://creativecommons.org/licenses/by-nc-sa/4.0/]
image::https://img.shields.io/badge/License-CC%20BY--NC--SA%204.0-lightgrey.svg[License: *CC BY-NC-SA 4.0*]

© 2020, Justin W. Flory, CC BY-NC-SA 4.0

This page is a concept note for the Federation of Intersectional Communities (shortened F.I.C.).
It provides an overview of the following topics:

. Goals
. Anti-Goals
. Common Values
. Member Communities
. Gain Membership


== Goals

The Federation of Intersectional Communities (FIC) is a group of aligned representatives from several different, but intersecting, communities.
Underneath our Common Values, FIC offers unity and collaboration with other like-minded people to further our shared mission in pursuing these Common Values.

Before reviewing the Common Values, first consider these deliberate intentions and goals of FIC:

=== Offer networking, community meta discussion, and peer advice.

FIC members come from a variety of communities.
Often, important and useful work is repeated many times over in different isolated pockets.
FIC offers community to the friends of communities.
It is our hope to offer shared wisdom with Member Communities to better enable our shared mission in pursuing our Common Values.

=== Offer shared resources (digital and non-digital).

FIC may act as a shared collective of some resources among Member Communities.
These could take the form of digital resources, like web infrastructure, or non-digital resources, like workshops, trainings, and/or mentorship.
Shared resources underneath FIC are intended to be shared equitably among Member Communities in ways that furthers our shared mission in pursuing our Common Values.


== Anti-Goals

There are also a few things that FIC explicitly does _not_ try to be.
This section is an overview of those things:

=== Make decisions on behalf of other communities.

FIC does not have decision-making in management of Member Communities.
It is not designed to be a diacritical institution.
We respect the unique contexts and shared experiences of Member Communities in their local contexts.
However, if a Member Community takes repeated and/or severe actions that appear to contradict our shared mission in pursuing our Common Values, it may be grounds of removal from FIC membership.

=== Define policy or engage in a widely visible forum.

FIC is a federation and represents many groups and organizations.
We believe it is the delegation of our Member Communities to pursue policy or engage more visibly.
FIC aims to be a common forum and shared resource for Member Communities to network and seek support.
FIC is not intended to be represented as a brand or even a single voice.
The only thing indisputably shared among all Member Communities is a commitment to our shared mission in pursuing our Common Values.


== Common Values

The Common Values are the foundation of the Federation of Intersectional Communities.
All Member Communities are firmly committed to pursuing meaningful work and collaborative contributions to objectives and tasks that align to our Common Values.
Changes to Common Values are proposed by discussion or Pull/Merge Requests.
All changes to Common Values require affirmative acknowledgement of all Member Communities.

=== Compassion.

Member Communities affirm the importance of Compassion in our communities.

Compassion::
: sympathetic consciousness of others' distress together with a desire to alleviate it.

Our work, our interactions, and aims are to alleviate distress, not add to it.
While we recognize our humanity and moments where we may make mistakes, we affirm compassion as a foundational part of who we are and what we do.

=== Teamwork.

Member Communities believe in the value of Teamwork in accomplishing our overlapping missions.

Teamwork::
: work done by several associates with each doing a part but all subordinating personal prominence to the efficiency of the whole.

FIC is best able to meet its goals when we approach our work with attitudes of collaboration and cooperation.
We recognize that each Member Community is doing important work in a subsection of our Common Values.
Each Member Community approaches interactions internally and externally with a collaborative spirit.

=== Care.

Member Communities value the role of Care in shaping sustainable communities.

Care::
especially : responsibility for or attention to health, well-being, and safety.

Communities are collections of people.
Groups of people are what form and define a community.
Therefore, it is important to value the role of Care in our actions (or non-actions), and in our collaborations.
We are better able to succeed in realizing our Common Values through our overlapping work when we take care of each other.

This is inclusive of Self-Care in the form of non-action, if taking action comes at a great personal cost or health risk (physical or mental).
The recognition of what is valid for Self-Care intersects with other Common Values.

=== Integrity.

Member Communities depend on Integrity in order to accomplish our shared missions underneath the Common Values.

Integrity::
firm adherence to a code of especially moral or artistic values : incorruptibility.

We believe our individual and collective actions must be bound by rigid Integrity.
To help serve as reference for FIC's interpretation of Integrity, we pledge commitment underneath the values of two doctrines:

. https://www.un.org/en/about-us/universal-declaration-of-human-rights[Universal Declaration of Human Rights]
. https://techautonomy.org/[Declaration of Digital Autonomy] (v0.1 or a later version)

Our work must never stand against the Universal Declaration of Human Rights.
Our collaborations and collective work are informed by the Declaration of Digital Autonomy.

==== Universal Declaration of Human Rights (excerpt)

[quote, Universal Declaration of Human Rights]
____
All human beings are born free and equal in dignity and rights. They are endowed with reason and conscience and should act towards one another in a spirit of brotherhood.
____

==== Declaration of Digital Autonomy (excerpt)

[quote, Declaration of Digital Autonomy]
____
We therefore call for the adoption of the following principles for ethical technology:

. In service of the people who use it
. Informed consent
. Empowering individual and collective digital action
. Protect people's privacy and other rights by design
____

=== Learning.

Member Communities recognize our humanity and natural ability to err; and we believe mistakes are valuable opportunities for Learning.

Learning::
: modification of a behavioral tendency by experience (such as exposure to conditioning).

Being intersectional is sometimes challenging.
We come from different backgrounds.
We have different view points on some topics.
And in this natural tension, there is great opportunity for Learning and personal growth.

In recognizing the mistakes of our own teams and fellow peers, we recognize the shared commitment to our Common Values.
We encourage our peers to make mistakes Learning opportunities to inform us how to most effectively pursue our shared missions.


== Member Communities

Below is a documented list of Member Communities to the Federation of Intersectional Communities.

_Currently, none!_
This is an idea in pilot mode right now.

=== Convener

The current Convener is *{_txt-convener}*.


== Gain Membership

This is an idea in pilot mode.
Currently, the only way to gain Membership is by contacting the Convener, {_txt-convener}.
If this idea goes beyond a pilot, this section will must be revised for sustainability purposes.
