---
title: Legal notice
author: Justin W. Flory
description: Legal notice to Service Providers that store Contributions created by me, Justin W. Flory.
lastmod: 2020-09-07
tags: ["bsd-3.0", "creative-commons", "cc-by"]

---
:toc:

*This notice is applicable to any company, enterprise, organization, or individual with digital services (the Service Provider) that stores any Contribution created by me, Justin W. Flory (the Original Creator).*


== Goal

Any Contribution shared by the Original Creator via the World Wide Web with a Service Provider is shared under a Current Default License.
A Contribution assumes a Current Default License if the Contribution is not explicitly licensed by the Original Creator.
The Service Provider is held accountable for all Contributions by the Original Creator under the terms of a Current Default License.


== Definitions

The section below contains definitions needed to understand other aspects of this legal notice.

=== CC BY

"CC BY" means the https://creativecommons.org/licenses/by/4.0/legalcode[Creative Commons Attribution 4.0 International license] (CC BY 4.0), as published at https://creativecommons.org/licenses/by/4.0/legalcode.
You have the option of following the terms and conditions either of that numbered version, or of any later version published by the Creative Commons.

=== Code

"Code" means:

[lowerroman]
. Software code;
. Any other functional material whose principal purpose is to control or facilitate the building of packages, such as an RPM spec file;
. Font files;
. Other kinds of copyrightable material that the Original Creator has classified as "code" rather than "content".

=== Content

"Content" means any copyrightable material that is not Code, such as, without limitation:

[lowerroman]
. Non-functional data sets;
. Documentation;
. Wiki edits;
. Music files;
. Graphic image files;
. Help files;
. Other kinds of copyrightable material that the Original Creator has classified as content rather than "code".

=== Contribution

"Contribution" means a Work that created by the Original Creator, excluding any portion that was created by someone else.
A Contribution consists either of Code or of Content.

=== Current Default License

"Current Default License", with respect to a Contribution, means:

[lowerroman]
. If the Contribution is Code, the https://opensource.org/licenses/BSD-3-Clause[3-Clause BSD License];
. If the Contribution is Content, the CC BY.
